import org.jetbrains.kotlin.gradle.dsl.JvmTarget

buildscript {
  dependencies {
    classpath libs.kotlinPlugin
    classpath libs.dokkaPlugin
    classpath libs.mavenPublishPlugin
    classpath libs.spotlessPlugin
    classpath libs.buildConfigPlugin
    classpath libs.pokoPlugin
  }
  repositories {
    mavenCentral()
    gradlePluginPortal()
  }
}

subprojects {
  group = GROUP
  version = VERSION_NAME

  apply plugin: 'com.diffplug.spotless'
  spotless {
    kotlin {
      ktfmt(libs.ktfmt.get().version).googleStyle()
      target('**/*.kt')
    }
  }

  plugins.withId('org.jetbrains.kotlin.jvm') {
    kotlin {
      plugins.withId('com.vanniktech.maven.publish') {
        abiValidation {
          enabled = true
        }
      }
      compilerOptions {
        jvmTarget = JvmTarget.fromTarget(libs.versions.jdkRelease.get())
        freeCompilerArgs = [
            "-progressive",
            '-opt-in=kotlin.contracts.ExperimentalContracts',
            "-Xjdk-release=${libs.versions.jdkRelease.get()}",
        ]
      }
    }
  }

  tasks.withType(JavaCompile).configureEach {
    options.release = libs.versions.jdkRelease.get().toInteger()
  }

  configurations.configureEach {
    resolutionStrategy.eachDependency {
      if (requested.group == "com.android.tools.build" && requested.name == "aapt2-proto") {
        useVersion(libs.versions.aapt2Proto.get())
        because("We need to keep depenedencies in sync with bundletool")
      }
      if (requested.group == "com.google.protobuf" && requested.name == "protobuf-java") {
        useVersion(libs.versions.protobufJava.get())
        because("We need to keep depenedencies in sync with bundletool")
      }
      if (requested.group == "com.google.guava" && requested.name == "guava") {
        useVersion(libs.versions.guava.get())
        because("We need to keep depenedencies in sync with bundletool")
      }
    }
  }
}
