import org.jetbrains.kotlin.gradle.dsl.JvmTarget

buildscript {
  dependencies {
    classpath libs.kotlinPlugin
    classpath libs.dokkaPlugin
    classpath libs.mavenPublishPlugin
    classpath libs.spotlessPlugin
    classpath libs.buildConfigPlugin
    classpath libs.pokoPlugin
  }
  repositories {
    mavenCentral()
    gradlePluginPortal()
  }
}

subprojects {
  group = GROUP
  version = VERSION_NAME

  apply plugin: 'com.diffplug.spotless'
  spotless {
    kotlin {
      ktfmt(libs.ktfmt.get().version).googleStyle()
      target('src/**/*.kt')
    }
  }

  plugins.withId('org.jetbrains.kotlin.jvm') {
    kotlin {
      plugins.withId('com.vanniktech.maven.publish') {
        abiValidation {
          enabled = true
        }
      }
      compilerOptions {
        allWarningsAsErrors = true
        jvmTarget = JvmTarget.JVM_11
        freeCompilerArgs = [
            "-progressive",
            '-opt-in=kotlin.contracts.ExperimentalContracts',
            '-Xjdk-release=11',
        ]
      }
    }
  }

  tasks.withType(JavaCompile).configureEach {
    options.release = 11
  }
}
