pluginManagement {
  dependencyResolutionManagement {
    repositories {
      mavenCentral()
      gradlePluginPortal()
    }
  }
}

plugins {
  id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
  repositories {
    mavenCentral()
    google()
  }
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = 'diffuse-root'

include ':diffuse'
include ':formats'
include ':io'
include ':reports'
include ':test-helpers'
