pluginManagement {
  repositories {
    mavenCentral()
    gradlePluginPortal()
  }
}
dependencyResolutionManagement {
  repositories {
    mavenCentral()
    google()
  }
}

enableFeaturePreview("STABLE_CONFIGURATION_CACHE")
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = 'diffuse-root'

include ':diffuse'
include ':formats'
include ':io'
include ':reports'
include ':test-helpers'
