[libraries]
dalvikDx = "com.jakewharton.android.repackaged:dalvik-dx:16.0.1"
binaryResources = "com.android.tools.apkparser:binary-resources:32.2.1"
apkSigner = "com.android.tools.build:apksig:9.2.1"
bundleTool = "com.android.tools.build:bundletool:1.18.3"
aapt2Proto = "com.android.tools.build:aapt2-proto:9.2.1-15009934"
protobufJava = "com.google.protobuf:protobuf-java:4.36.0"
clikt = "com.github.ajalt.clikt:clikt:5.1.0"
junit = "junit:junit:4.13.2"
assertk = "com.willowtreeapps.assertk:assertk:0.28.1"
okio = "com.squareup.okio:okio:3.18.1"
bytesize = "me.saket.bytesize:bytesize:2.2.1"
asm = "org.ow2.asm:asm:9.10.1"
diffUtils = "io.github.java-diff-utils:java-diff-utils:4.17"
picnic = "com.jakewharton.picnic:picnic:0.7.0"
mordant = "com.github.ajalt.mordant:mordant:3.0.2"
kotlinPlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:2.4.10"
dokkaPlugin = "org.jetbrains.dokka:dokka-gradle-plugin:2.2.0"
mavenPublishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.37.0"
spotlessPlugin = "com.diffplug.spotless:spotless-plugin-gradle:8.10.1"
buildConfigPlugin = "com.github.gmazzo.buildconfig:plugin:6.0.10"
pokoPlugin = "dev.drewhamilton.poko:dev.drewhamilton.poko.gradle.plugin:0.23.1"
ktfmt = "com.facebook:ktfmt:0.64"
