[versions]
# Keep this values in sync with bundletool"s dependencies.
aapt2Proto = "8.13.0-13719691"
protobufJava = "4.32.0"
guava = "30.1-jre"

[libraries]
dalvikDx = "com.jakewharton.android.repackaged:dalvik-dx:14.0.0_r21"
binaryResources = "com.android.tools.apkparser:binary-resources:31.13.0"
apkSigner = "com.android.tools.build:apksig:8.13.0"
bundleTool = "com.android.tools.build:bundletool:1.18.1"
aapt2Proto = { module = "com.android.tools.build:aapt2-proto", version.ref = "aapt2Proto" }
protobufJava = { module = "com.google.protobuf:protobuf-java", version.ref = "protobufJava" }
clikt = "com.github.ajalt.clikt:clikt:5.0.3"
junit = "junit:junit:4.13.2"
assertk = "com.willowtreeapps.assertk:assertk:0.28.1"
okio = "com.squareup.okio:okio:3.16.0"
byteunits = "com.jakewharton.byteunits:byteunits:0.9.1"
asm = "org.ow2.asm:asm:9.8"
diffUtils = "io.github.java-diff-utils:java-diff-utils:4.16"
picnic = "com.jakewharton.picnic:picnic:0.7.0"
mordant = "com.github.ajalt.mordant:mordant:3.0.2"
kotlinPlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.10"
dokkaPlugin = "org.jetbrains.dokka:dokka-gradle-plugin:2.0.0"
mavenPublishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.34.0"
spotlessPlugin = "com.diffplug.spotless:spotless-plugin-gradle:7.2.1"
buildConfigPlugin = "com.github.gmazzo.buildconfig:plugin:5.6.7"

# Dummy to get renovate updates, the version is used in rootProject build.gradle with spotless.
ktlint = "com.pinterest.ktlint:ktlint-cli:1.7.1"
