POM_ARTIFACT_ID=formats
POM_NAME=Diffuse format parsing
POM_PACKAGING=jar

# Keep associated Kotlin compilations from depending on archive tasks (e.g., jar), which can create circular task graphs in multi-release setups.
# https://kotlinlang.org/docs/gradle-configure-project.html#disable-use-of-artifact-in-compilation-task
# https://kotlinlang.org/docs/whatsnew2020.html#added-task-dependency-for-rare-cases-when-the-compile-task-lacks-one-on-an-artifact
kotlin.build.archivesTaskOutputAsFriendModule=false
